title: Aqua
description: Autonomous QUorum of Agents - Lightweight coordinator for CLI AI agents
baseurl: /aqua
url: https://vignesh07.github.io
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
